# Generated by Django 5.1 on 2024-08-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_code_course_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='DEFAULT_CODE', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
