# Generated by Django 5.1 on 2024-08-24 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_description_alter_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', to_field='course_code'),
        ),
    ]
