# Generated by Django 5.1 on 2024-08-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courseinstance_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstance',
            name='id',
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='course',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
